name = "account-store-d1-api"
main = "src/index.js"
compatibility_date = "2026-09-19"

[[d1_databases]]
binding = "DB"
database_name = "account-store-db"
database_id = "b1135edf-8a57-4be9-96ae-148e209dfdea"

[vars]
# Set this as a Worker secret instead of committing the real value:
# D1_API_SECRET
