const db=require("../database");
const session=require("../utils/session");
const {requireAdmin}=require("./admin");
const {escapeHtml}=require("../utils/helpers");
const k=require("../keyboards/server2");

function registerServer2Handler(bot){
 const admin=ctx=>requireAdmin(ctx);
 bot.action("admin:countries:server2",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;await c.editMessageText("🖥️ <b>Server 2 Countries</b>",{parse_mode:"HTML",...k.server2CountryMenu()});});
 bot.action("s2:admin:home",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;await c.editMessageText("🖥️ <b>Server 2</b>\n\nManual stock management",{parse_mode:"HTML",...k.server2Home()});});
 bot.action("s2:admin:countries",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;await c.editMessageText("🌍 <b>Server 2 Countries</b>",{parse_mode:"HTML",...k.server2CountryMenu()});});
 bot.action("s2:admin:countries:list",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const a=await db.listServer2Countries();await c.editMessageText(`📋 <b>Countries</b> — ${a.length}`,{parse_mode:"HTML",...k.server2CountryList(a)});});
 bot.action("s2:admin:country:add",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;session.set(c.from.id,{step:"s2_country_add",data:{}});await c.reply("Format: <code>India | 🇮🇳</code>",{parse_mode:"HTML"});});
 bot.action(/^s2:admin:country:view:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const x=await db.getServer2Country(c.match[1]);if(!x)return c.editMessageText("❌ Country not found.",k.server2CountryMenu());await c.editMessageText(`🌍 <b>${escapeHtml(x.name)}</b>\nStatus: <b>${escapeHtml(x.status)}</b>`,{parse_mode:"HTML",...k.server2CountryDetail(x)});});
 bot.action(/^s2:admin:country:toggle:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const x=await db.getServer2Country(c.match[1]);if(!x)return;const y=await db.updateServer2Country(x.id,{status:x.status==="enabled"?"disabled":"enabled"});await c.editMessageText(`🌍 <b>${escapeHtml(y.name)}</b> → <b>${y.status}</b>`,{parse_mode:"HTML",...k.server2CountryDetail(y)});});
 bot.action(/^s2:admin:country:delete:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;await db.deleteServer2Country(c.match[1]);await c.editMessageText("✅ Country deleted.",k.server2CountryMenu());});

 bot.action("s2:admin:stock",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;await c.editMessageText("📦 <b>Server 2 Stock</b>",{parse_mode:"HTML",...k.server2StockMenu()});});
 bot.action(/^s2:admin:stock:list:(available|all)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const a=await db.listServer2Stock({status:c.match[1]==="available"?"available":undefined});await c.editMessageText(`📦 <b>Stock</b> — ${a.length}`,{parse_mode:"HTML",...k.server2StockList(a)});});
 bot.action(/^s2:admin:stock:view:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const x=await db.getServer2Stock(c.match[1]);if(!x)return c.editMessageText("❌ Stock not found.",k.server2StockMenu());await c.editMessageText(`📦 <b>Stock</b>\n\n🌍 ${escapeHtml(x.countryName)}\n🔢 <code>${escapeHtml(x.name)}</code>\n💰 ₹${Number(x.price).toFixed(2)}\n📌 ${escapeHtml(x.status)}`,{parse_mode:"HTML",...k.server2StockDetail(x)});});
 bot.action("s2:admin:stock:add",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;session.set(c.from.id,{step:"s2_stock_add",data:{}});await c.reply("Format: <code>COUNTRY_ID | Item/Number | Price | Delivery Info</code>",{parse_mode:"HTML"});});
 bot.action(/^s2:admin:stock:price:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;session.set(c.from.id,{step:"s2_stock_price",data:{stockId:c.match[1]}});await c.reply("New price bhejo:");});
 bot.action(/^s2:admin:stock:delete:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;try{await db.deleteServer2Stock(c.match[1]);await c.editMessageText("✅ Stock deleted.",k.server2StockMenu());}catch(e){await c.answerCbQuery("Delete failed",{show_alert:true});}});

 bot.action("s2:admin:orders",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;await c.editMessageText("🛒 <b>Server 2 Orders</b>",{parse_mode:"HTML",...k.server2OrdersMenu()});});
 bot.action(/^s2:admin:orders:(pending|processing|completed|cancelled|all)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const s=c.match[1]==="all"?undefined:c.match[1];const a=await db.listServer2Orders({status:s,limit:50});await c.editMessageText(`🛒 <b>Orders</b> — ${a.length}`,{parse_mode:"HTML",...k.server2OrderList(a)});});
 bot.action(/^s2:admin:order:view:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const x=await db.getServer2Order(c.match[1]);if(!x)return c.editMessageText("❌ Order not found.",k.server2OrdersMenu());await c.editMessageText(`🛒 <b>Order</b>\n\nID: <code>${escapeHtml(x.orderId)}</code>\nUser: <code>${escapeHtml(x.userId)}</code>\nItem: <b>${escapeHtml(x.itemName)}</b>\nAmount: <b>₹${Number(x.amount).toFixed(2)}</b>\nStatus: <b>${escapeHtml(x.status)}</b>\n\nDelivery: ${escapeHtml(x.deliveryInfo||"Pending")}`,{parse_mode:"HTML",...k.server2OrderDetail(x)});});
 bot.action(/^s2:admin:order:processing:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const x=await db.getServer2Order(c.match[1]);if(!x||x.status!=="pending")return;const y=await db.updateServer2Order(x.orderId,{status:"processing",processedBy:String(c.from.id)});await c.editMessageText("⚙️ <b>Processing</b>",{parse_mode:"HTML",...k.server2OrderDetail(y)});});
 bot.action(/^s2:admin:order:complete:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;session.set(c.from.id,{step:"s2_order_complete",data:{orderId:c.match[1]}});await c.reply("Delivery details bhejo:");});
 bot.action(/^s2:admin:order:cancel:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;try{const x=await db.cancelServer2OrderAndRefund(c.match[1],String(c.from.id));await c.editMessageText(`❌ Cancelled. ₹${Number(x.refundAmount).toFixed(2)} refunded.`,{parse_mode:"HTML",...k.server2OrdersMenu()});}catch(e){await c.answerCbQuery("Cancel failed",{show_alert:true});}});
 bot.action("s2:admin:stats",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const s=await db.getServer2Stats();await c.editMessageText(`📊 <b>Server 2</b>\n\n📦 Available: <b>${s.availableStock}</b>\n🛒 Orders: <b>${s.totalOrders}</b>\n⏳ Pending: <b>${s.pending}</b>\n⚙️ Processing: <b>${s.processing}</b>\n✅ Completed: <b>${s.completed}</b>\n❌ Cancelled: <b>${s.cancelled}</b>\n💰 Sales: <b>₹${s.sales.toFixed(2)}</b>`,{parse_mode:"HTML",...k.server2Home()});});

 bot.action("menu_server2",async c=>{await c.answerCbQuery();const s=await db.getSettings();if(s.server2Enabled===false)return c.answerCbQuery("Server 2 disabled",{show_alert:true});await c.editMessageText("🖥️ <b>Server 2</b>\n\nManual stock marketplace",{parse_mode:"HTML",...k.server2UserHome()});});
 bot.action("s2:user:home",async c=>{await c.answerCbQuery();await c.editMessageText("🖥️ <b>Server 2</b>",{parse_mode:"HTML",...k.server2UserHome()});});
 bot.action("s2:user:countries",async c=>{await c.answerCbQuery();const a=await db.listServer2Countries({onlyEnabled:true});await c.editMessageText("🌍 <b>Select Country</b>",{parse_mode:"HTML",...k.server2UserCountries(a)});});
 bot.action(/^s2:user:country:(.+)$/,async c=>{await c.answerCbQuery();const a=await db.listServer2Stock({countryId:c.match[1],status:"available"});await c.editMessageText("📦 <b>Available Stock</b>",{parse_mode:"HTML",...k.server2UserStock(a)});});
 bot.action(/^s2:user:buy:(.+)$/,async c=>{await c.answerCbQuery();const x=await db.getServer2Stock(c.match[1]);if(!x||x.status!=="available")return c.editMessageText("❌ Stock unavailable.",k.server2UserHome());await c.editMessageText(`📦 <b>Confirm Purchase</b>\n\nItem: <b>${escapeHtml(x.name)}</b>\nCountry: <b>${escapeHtml(x.countryName)}</b>\nPrice: <b>₹${Number(x.price).toFixed(2)}</b>`,{parse_mode:"HTML",...k.server2Confirm(x.stockId)});});
 bot.action(/^s2:user:confirm:(.+)$/,async c=>{await c.answerCbQuery();try{const x=await db.createServer2Order(String(c.from.id),c.match[1]);await c.editMessageText(`✅ <b>Order Created</b>\n\nID: <code>${escapeHtml(x.orderId)}</code>\nAmount: <b>₹${Number(x.amount).toFixed(2)}</b>\nStatus: <b>Pending</b>`,{parse_mode:"HTML",...k.server2UserHome()});}catch(e){await c.editMessageText(e.code==="INSUFFICIENT_BALANCE"?"❌ Insufficient balance.":e.code==="OUT_OF_STOCK"?"❌ Stock unavailable.":"❌ Purchase failed.",k.server2UserHome());}});
 bot.action("s2:user:orders",async c=>{await c.answerCbQuery();const a=await db.listUserServer2Orders(String(c.from.id),30);await c.editMessageText("📦 <b>My Server 2 Orders</b>",{parse_mode:"HTML",...k.server2UserOrders(a)});});
 bot.action(/^s2:user:order:(.+)$/,async c=>{await c.answerCbQuery();const x=await db.getServer2Order(c.match[1]);if(!x||String(x.userId)!==String(c.from.id))return c.editMessageText("❌ Order not found.",k.server2UserHome());await c.editMessageText(`📦 <b>Order</b>\n\nID: <code>${escapeHtml(x.orderId)}</code>\nItem: <b>${escapeHtml(x.itemName)}</b>\nAmount: <b>₹${Number(x.amount).toFixed(2)}</b>\nStatus: <b>${escapeHtml(x.status)}</b>\n\nDelivery: ${escapeHtml(x.deliveryInfo||"Pending")}`,{parse_mode:"HTML",...k.server2UserHome()});});

 return {textSteps:{
  s2_country_add:async(c)=>{const [name,emoji="🌍"]=String(c.message.text||"").split("|").map(x=>x.trim());if(!name)return c.reply("Invalid country.");await db.createServer2Country({name,emoji});session.clear(c.from.id);await c.reply("✅ Country added.",k.server2CountryMenu());},
  s2_stock_add:async(c)=>{const p=String(c.message.text||"").split("|").map(x=>x.trim());if(p.length<3)return c.reply("Format: COUNTRY_ID | Item/Number | Price | Delivery Info");const [countryId,name,price,deliveryInfo=""]=p;try{await db.createServer2Stock({countryId,name,price,deliveryInfo});session.clear(c.from.id);await c.reply("✅ Stock added.",k.server2StockMenu());}catch(e){await c.reply("❌ "+e.message);}},
  s2_stock_price:async(c,state)=>{const price=Number(String(c.message.text||"").trim());if(!Number.isFinite(price)||price<=0)return c.reply("Invalid price.");await db.updateServer2Stock(state.data.stockId,{price});session.clear(c.from.id);await c.reply("✅ Price updated.",k.server2StockMenu());},
  s2_order_complete:async(c,state)=>{const info=String(c.message.text||"").trim();if(!info)return c.reply("Delivery details required.");await db.completeServer2Order(state.data.orderId,String(c.from.id),info);session.clear(c.from.id);await c.reply("✅ Order completed.",k.server2OrdersMenu());}
 }};
}
module.exports={registerServer2Handler};