const db=require("../database");
const session=require("../utils/session");
const {requireAdmin}=require("./admin");
const {escapeHtml}=require("../utils/helpers");
const k=require("../keyboards/server2");

function registerServer2Handler(bot){
 const admin=ctx=>requireAdmin(ctx);
 bot.action("admin:countries:server2",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;await db.ensureServer2TopCountries(k.SERVER2_TOP_COUNTRIES);await c.editMessageText("🌍 <b>Server 2 Countries</b>\n\nSelect a country to add or manage it:",{parse_mode:"HTML",...k.server2TopCountryMenu()});});
 bot.action("s2:admin:home",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;await c.editMessageText("🖥️ <b>SERVER 2 CONTROL PANEL</b>\n\n🌍 <b>Countries</b>  •  📦 <b>Stock</b>\n🛒 <b>Orders</b>  •  📊 <b>Statistics</b>\n\nManage your Server 2 marketplace from one place.",{parse_mode:"HTML",...k.server2Home()});});
 bot.action("s2:admin:countries",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;await db.ensureServer2TopCountries(k.SERVER2_TOP_COUNTRIES);await c.editMessageText("🌍 <b>Server 2 Countries</b>",{parse_mode:"HTML",...k.server2CountryMenu()});});
 bot.action("s2:admin:countries:list",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;await db.ensureServer2TopCountries(k.SERVER2_TOP_COUNTRIES);const a=await db.listServer2Countries();await c.editMessageText(`📋 <b>Countries</b> — ${a.length}`,{parse_mode:"HTML",...k.server2CountryList(a)});});

 bot.action("s2:admin:country:add",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;await c.editMessageText("🌍 <b>Server 2 Countries</b>\n\nSelect a country to add or manage it:",{parse_mode:"HTML",...k.server2TopCountryMenu()});});
 bot.action("s2:admin:country:manual",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;session.set(c.from.id,{step:"s2_country_add",data:{}});await c.reply("✍️ <b>Manual Country Add</b>\n\nFormat: <code>India | 🇮🇳</code>\n\nExample: <code>Nepal | 🇳🇵</code>",{parse_mode:"HTML"});});
 bot.action(/^s2:admin:country:preset:(\d+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const index=Number(c.match[1]);const preset=k.SERVER2_TOP_COUNTRIES[index];if(!preset)return c.answerCbQuery("Country not found",{show_alert:true});const [emoji,name]=preset;const existing=(await db.listServer2Countries()).find(x=>String(x.name||"").trim().toLowerCase()===name.toLowerCase());if(existing){return c.editMessageText(`ℹ️ <b>${escapeHtml(name)}</b> already exists.\nStatus: <b>${escapeHtml(existing.status||"enabled")}</b>`,{parse_mode:"HTML",...k.server2CountryDetail(existing)});}const created=await db.createServer2Country({name,emoji});await c.editMessageText(`✅ <b>${escapeHtml(created.name)}</b> added.\n\n${created.emoji} Country is now enabled.`,{parse_mode:"HTML",...k.server2CountryDetail(created)});});

 bot.action(/^s2:admin:country:view:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const x=await db.getServer2Country(c.match[1]);if(!x)return c.editMessageText("❌ Country not found.",{...k.server2TopCountryMenu()});await c.editMessageText(`🌍 <b>${escapeHtml(x.name)}</b>\nStatus: <b>${escapeHtml(x.status)}</b>`,{parse_mode:"HTML",...k.server2CountryDetail(x)});});
 bot.action(/^s2:admin:country:toggle:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const x=await db.getServer2Country(c.match[1]);if(!x)return;const y=await db.updateServer2Country(x.id,{status:x.status==="enabled"?"disabled":"enabled"});await c.editMessageText(`🌍 <b>${escapeHtml(y.name)}</b> → <b>${y.status}</b>`,{parse_mode:"HTML",...k.server2CountryDetail(y)});});
 bot.action(/^s2:admin:country:delete:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;await db.deleteServer2Country(c.match[1]);await c.editMessageText("✅ Country deleted.",k.server2TopCountryMenu());});

 bot.action("s2:admin:stock",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;await c.editMessageText("📦 <b>SERVER 2 STOCK</b>\n\nManage inventory, prices and availability.",{parse_mode:"HTML",...k.server2StockMenu()});});
 bot.action(/^s2:admin:stock:country:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const country=await db.getServer2Country(c.match[1]);if(!country||country.status!=="enabled")return c.answerCbQuery("Country unavailable",{show_alert:true});session.set(c.from.id,{step:"s2_stock_numbers",data:{countryId:country.id,countryName:country.name,countryEmoji:country.emoji}});await c.editMessageText("🔢 <b>Step 2/5 — Add Number(s)</b>\n\nCountry: "+escapeHtml(country.emoji)+" "+escapeHtml(country.name)+"\n\nSend one number or multiple numbers.\nFor bulk, send <b>one number per line</b>.\n\nExample:\n<code>+977XXXXXXXXX\n+977YYYYYYYYY</code>",{parse_mode:"HTML"});}); bot.action(/^s2:admin:stock:list:(available|all)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const a=await db.listServer2Stock({status:c.match[1]==="available"?"available":undefined});await c.editMessageText(`📦 <b>Stock</b> — ${a.length}`,{parse_mode:"HTML",...k.server2StockList(a)});});
 bot.action(/^s2:admin:stock:view:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const x=await db.getServer2Stock(c.match[1]);if(!x)return c.editMessageText("❌ Stock not found.",k.server2StockMenu());await c.editMessageText(`📦 <b>Stock</b>\n\n🌍 ${escapeHtml(x.countryName)}\n🔢 <code>${escapeHtml(x.name)}</code>\n💰 ₹${Number(x.price).toFixed(2)}\n📌 ${escapeHtml(x.status)}`,{parse_mode:"HTML",...k.server2StockDetail(x)});});
 bot.action("s2:admin:stock:add",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const countries=await db.listServer2Countries({onlyEnabled:true});if(!countries.length)return c.editMessageText("❌ <b>No enabled countries</b>\\n\\nAdd/enable a country first.",{parse_mode:"HTML",...k.server2TopCountryMenu()});session.set(c.from.id,{step:"s2_stock_country",data:{}});await c.editMessageText("➕ <b>ADD STOCK</b>\\n\\n🌍 <b>Step 1/5 — Select Country</b>\\nChoose the country for this stock.",{parse_mode:"HTML",...k.server2StockCountrySelect(countries)});});
 bot.action(/^s2:admin:stock:price:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;session.set(c.from.id,{step:"s2_stock_price",data:{stockId:c.match[1]}});await c.reply("💰 <b>UPDATE PRICE</b>\n\nNew price bhejo, example: <code>150</code>",{parse_mode:"HTML"});});
 bot.action(/^s2:admin:stock:delete:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;try{await db.deleteServer2Stock(c.match[1]);await c.editMessageText("✅ Stock deleted.",k.server2StockMenu());}catch(e){await c.answerCbQuery("Delete failed",{show_alert:true});}});

 bot.action("s2:admin:orders",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;await c.editMessageText("🛒 <b>SERVER 2 ORDERS</b>\n\nTrack pending, processing and completed orders.",{parse_mode:"HTML",...k.server2OrdersMenu()});});
 bot.action(/^s2:admin:orders:(pending|processing|completed|cancelled|all)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const s=c.match[1]==="all"?undefined:c.match[1];const a=await db.listServer2Orders({status:s,limit:50});await c.editMessageText(`🛒 <b>Orders</b> — ${a.length}`,{parse_mode:"HTML",...k.server2OrderList(a)});});
 bot.action(/^s2:admin:order:view:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const x=await db.getServer2Order(c.match[1]);if(!x)return c.editMessageText("❌ Order not found.",k.server2OrdersMenu());await c.editMessageText(`🛒 <b>Order</b>\n\nID: <code>${escapeHtml(x.orderId)}</code>\nUser: <code>${escapeHtml(x.userId)}</code>\nItem: <b>${escapeHtml(x.itemName)}</b>\nAmount: <b>₹${Number(x.amount).toFixed(2)}</b>\nStatus: <b>${escapeHtml(x.status)}</b>\n\nDelivery: ${escapeHtml(x.deliveryInfo||"Pending")}`,{parse_mode:"HTML",...k.server2OrderDetail(x)});});
 bot.action(/^s2:admin:order:processing:(.+)$/,async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const x=await db.getServer2Order(c.match[1]);if(!x||x.status!=="pending")return;const y=await db.updateServer2Order(x.orderId,{status:"processing",processedBy:String(c.from.id)});await c.editMessageText("⚙️ <b>Processing</b>",{parse_mode:"HTML",...k.server2OrderDetail(y)});});

 bot.action("s2:admin:stats",async c=>{await c.answerCbQuery();if(!(await admin(c)))return;const s=await db.getServer2Stats();await c.editMessageText(`📊 <b>Server 2</b>\n\n📦 Available: <b>${s.availableStock}</b>\n🛒 Orders: <b>${s.totalOrders}</b>\n⏳ Pending: <b>${s.pending}</b>\n⚙️ Processing: <b>${s.processing}</b>\n✅ Completed: <b>${s.completed}</b>\n❌ Cancelled: <b>${s.cancelled}</b>\n💰 Sales: <b>₹${s.sales.toFixed(2)}</b>`,{parse_mode:"HTML",...k.server2Home()});});

 bot.action("server2:menu",async c=>{await c.answerCbQuery();const s=await db.getSettings();if(s.server2Enabled===false)return c.answerCbQuery("Server 2 disabled",{show_alert:true});await c.editMessageText("🖥️ <b>Server 2</b>\n\nManual stock marketplace",{parse_mode:"HTML",...k.server2UserHome()});});
 bot.action("s2:user:home",async c=>{await c.answerCbQuery();await c.editMessageText("🖥️ <b>Server 2</b>",{parse_mode:"HTML",...k.server2UserHome()});});
 bot.action("s2:user:countries",async c=>{await c.answerCbQuery();const a=await db.listServer2Countries({onlyEnabled:true});await c.editMessageText("🌍 <b>Select Country</b>",{parse_mode:"HTML",...k.server2UserCountries(a)});});
 bot.action(/^s2:user:country:(.+)$/,async c=>{await c.answerCbQuery();const a=await db.listServer2Stock({countryId:c.match[1],status:"available"});await c.editMessageText("📦 <b>Available Stock</b>",{parse_mode:"HTML",...k.server2UserStock(a)});});
 bot.action(/^s2:user:buy:(.+)$/,async c=>{await c.answerCbQuery();try{const x=await db.reserveServer2Stock(String(c.from.id),c.match[1]);await c.editMessageText(`🔒 <b>Number Locked for 5 Minutes</b>\n\nItem: <b>${escapeHtml(x.name)}</b>\nCountry: <b>${escapeHtml(x.countryName)}</b>\nPrice: <b>₹${Number(x.price).toFixed(2)}</b>\n\n⏳ Complete the purchase within <b>5 minutes</b>.\nAfter 5 minutes the number can become available again.`,{parse_mode:"HTML",...k.server2Confirm(x.stockId)});}catch(e){await c.editMessageText("❌ This number is currently unavailable. Please choose another.",k.server2UserHome());}});
 bot.action(/^s2:user:confirm:(.+)$/,async c=>{await c.answerCbQuery();try{const x=await db.createServer2Order(String(c.from.id),c.match[1]);await c.editMessageText(`✅ <b>Purchase Successful</b>\n\n🧾 Order: <code>${escapeHtml(x.orderId)}</code>\n🌍 Country: <b>${escapeHtml(x.countryName)}</b>\n🔢 Number: <code>${escapeHtml(x.deliveryInfo)}</code>\n💰 Paid: <b>₹${Number(x.amount).toFixed(2)}</b>\n\n📌 Status: <b>Completed</b>`,{parse_mode:"HTML",...k.server2UserHome()});}catch(e){await c.editMessageText(e.code==="INSUFFICIENT_BALANCE"?"❌ Insufficient balance.":e.code==="OUT_OF_STOCK"?"❌ Stock unavailable.":"❌ Purchase failed.",k.server2UserHome());}});
 bot.action("s2:user:orders",async c=>{await c.answerCbQuery();const a=await db.listUserServer2Orders(String(c.from.id),30);await c.editMessageText("📦 <b>My Server 2 Orders</b>",{parse_mode:"HTML",...k.server2UserOrders(a)});});
 bot.action(/^s2:user:order:(.+)$/,async c=>{await c.answerCbQuery();const x=await db.getServer2Order(c.match[1]);if(!x||String(x.userId)!==String(c.from.id))return c.editMessageText("❌ Order not found.",k.server2UserHome());await c.editMessageText(`📦 <b>Order</b>\n\nID: <code>${escapeHtml(x.orderId)}</code>\nItem: <b>${escapeHtml(x.itemName)}</b>\nAmount: <b>₹${Number(x.amount).toFixed(2)}</b>\nStatus: <b>${escapeHtml(x.status)}</b>\n\nDelivery: ${escapeHtml(x.deliveryInfo||"Pending")}`,{parse_mode:"HTML",...k.server2UserHome()});});

 return {textSteps:{
  s2_country_add:async(c)=>{const raw=String(c.message.text||"").trim();const parts=raw.split("|").map(x=>x.trim()).filter(Boolean);if(parts.length<1||!parts[0])return c.reply("❌ Country name required.\n\nFormat: India | 🇮🇳",{parse_mode:"HTML"});const name=parts[0];const emoji=parts[1]||"🌍";if(name.length>60)return c.reply("❌ Country name too long.");if(emoji.length>12)return c.reply("❌ Flag/emoji invalid.");const existing=(await db.listServer2Countries()).find(x=>String(x.name||"").trim().toLowerCase()===name.toLowerCase());if(existing){session.clear(c.from.id);return c.reply(`ℹ️ <b>${escapeHtml(existing.name)}</b> already exists.\nStatus: <b>${escapeHtml(existing.status||"enabled")}</b>`,{parse_mode:"HTML",...k.server2CountryDetail(existing)});}try{const created=await db.createServer2Country({name,emoji});session.clear(c.from.id);const countries=await db.listServer2Countries();await c.reply(`✅ <b>${escapeHtml(created.name)}</b> added with ${escapeHtml(created.emoji)}.\n\n🌍 <b>Server 2 Countries</b> — ${countries.length} total`,{parse_mode:"HTML",...k.server2TopCountryMenu()});}catch(e){await c.reply("❌ Country add failed: "+escapeHtml(e.message||"Unknown error"),{parse_mode:"HTML"});}},
  s2_stock_country:async(c,state)=>{const countryId=String(c.message.text||"").trim();if(!countryId)return c.reply("❌ Select a country from the buttons.");const country=await db.getServer2Country(countryId);if(!country||country.status!=="enabled")return c.reply("❌ Invalid or disabled country.");session.set(c.from.id,{step:"s2_stock_numbers",data:{countryId,countryName:country.name,countryEmoji:country.emoji}});await c.reply("🔢 <b>Step 2/5 — Add Number(s)</b>\n\nSend one number or multiple numbers.\nFor bulk, send <b>one number per line</b>.\n\nExample:\n<code>+977XXXXXXXXX\n+977YYYYYYYYY\n+977ZZZZZZZZZ</code>",{parse_mode:"HTML"});},
  s2_stock_numbers:async(c,state)=>{const lines=String(c.message.text||"").split(/\r?\n|,/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return c.reply("❌ At least one number is required.");const numbers=[...new Set(lines)];if(numbers.length>200)return c.reply("❌ Maximum 200 numbers per batch.");session.set(c.from.id,{step:"s2_stock_price",data:{...state.data,numbers}});await c.reply("💰 <b>Step 3/5 — Set Price</b>\n\nCountry: "+escapeHtml(state.data.countryEmoji)+" "+escapeHtml(state.data.countryName)+"\nNumbers: <b>"+numbers.length+"</b>\n\nSend the price per number, e.g. <code>150</code>",{parse_mode:"HTML"});},
  s2_stock_price:async(c,state)=>{const price=Number(String(c.message.text||"").trim());if(!Number.isFinite(price)||price<=0)return c.reply("❌ Invalid price. Send a positive number, e.g. 150.");session.set(c.from.id,{step:"s2_stock_verify1",data:{...state.data,price}});await c.reply("🔐 <b>Step 4/5 — Verification Password 1</b>\n\nEnter the first admin verification password.",{parse_mode:"HTML"});},
  s2_stock_verify1:async(c,state)=>{const expected=process.env.SERVER2_VERIFY_PASSWORD_1;if(!expected)return c.reply("❌ Server 2 verification password 1 is not configured.");if(String(c.message.text||"")!==String(expected))return c.reply("❌ Verification password 1 is incorrect. Try again.");session.set(c.from.id,{step:"s2_stock_verify2",data:{...state.data}});await c.reply("🔐 <b>Step 5/5 — Verification Password 2</b>\n\nEnter the second admin verification password.",{parse_mode:"HTML"});},
  s2_stock_verify2:async(c,state)=>{const expected=process.env.SERVER2_VERIFY_PASSWORD_2;if(!expected)return c.reply("❌ Server 2 verification password 2 is not configured.");if(String(c.message.text||"")!==String(expected))return c.reply("❌ Verification password 2 is incorrect. Try again.");try{const created=[];for(const number of state.data.numbers){created.push(await db.createServer2Stock({countryId:state.data.countryId,name:number,price:state.data.price,deliveryInfo:""}));}session.clear(c.from.id);await c.reply("✅ <b>Stock Added Successfully</b>\n\n🌍 "+escapeHtml(state.data.countryEmoji)+" "+escapeHtml(state.data.countryName)+"\n🔢 Added: <b>"+created.length+"</b> number(s)\n💰 Price: <b>₹"+Number(state.data.price).toFixed(2)+"</b> per number\n\nEach number is stored as a separate stock item.",{parse_mode:"HTML",...k.server2StockMenu()});}catch(e){await c.reply("❌ Stock add failed: "+escapeHtml(e.message||"Unknown error"),{parse_mode:"HTML"});}},
 }};
}
module.exports={registerServer2Handler};
