const fs = require("fs");
const path = require("path");
const { google } = require("googleapis");
const { authenticate } = require("@google-cloud/local-auth");

const CREDENTIALS_PATH = path.join(process.cwd(), "credentials.json");
const TOKEN_PATH = path.join(process.cwd(), "gmail-token.json");

const SCOPES = [
  "https://www.googleapis.com/auth/gmail.readonly",
];

let gmailClient = null;

function loadCredentials() {
  if (process.env.GMAIL_CREDENTIALS_JSON) {
    const parsed = JSON.parse(process.env.GMAIL_CREDENTIALS_JSON);
    return parsed.installed || parsed.web || parsed;
  }

  const data = JSON.parse(fs.readFileSync(CREDENTIALS_PATH, "utf8"));
  return data.installed || data.web;
}

function loadToken() {
  if (process.env.GMAIL_TOKEN_JSON) {
    return JSON.parse(process.env.GMAIL_TOKEN_JSON);
  }

  if (!fs.existsSync(TOKEN_PATH)) return null;

  return JSON.parse(fs.readFileSync(TOKEN_PATH, "utf8"));
}

function isRailway() {
  return Boolean(
    process.env.RAILWAY_ENVIRONMENT ||
    process.env.RAILWAY_ENVIRONMENT_NAME ||
    process.env.RAILWAY_PROJECT_ID
  );
}

async function getGmailClient() {
  if (gmailClient) return gmailClient;

  let credentials;

  try {
    credentials = loadCredentials();
  } catch (err) {
    throw new Error(
      "Gmail credentials are not configured. Set GMAIL_CREDENTIALS_JSON or provide credentials.json."
    );
  }

  if (!credentials) {
    throw new Error("Invalid Gmail OAuth credentials.");
  }

  const { client_id, client_secret, redirect_uris } = credentials;

  if (!client_id || !client_secret) {
    throw new Error("Invalid Gmail OAuth credentials: client_id/client_secret missing.");
  }

  const oauth2Client = new google.auth.OAuth2(
    client_id,
    client_secret,
    redirect_uris?.[0] || "http://localhost"
  );

  const existingToken = loadToken();

  if (existingToken) {
    oauth2Client.setCredentials(existingToken);

    oauth2Client.on("tokens", (tokens) => {
      // When token JSON is supplied through Railway env vars, the refresh
      // token remains in that env value. Do not try to mutate env vars.
      if (process.env.GMAIL_TOKEN_JSON) return;

      try {
        const current = fs.existsSync(TOKEN_PATH)
          ? JSON.parse(fs.readFileSync(TOKEN_PATH, "utf8"))
          : {};

        fs.writeFileSync(
          TOKEN_PATH,
          JSON.stringify({ ...current, ...tokens }, null, 2),
          { mode: 0o600 }
        );
      } catch (_) {}
    });

    gmailClient = google.gmail({
      version: "v1",
      auth: oauth2Client,
    });

    return gmailClient;
  }

  // A headless Railway process cannot complete the interactive browser OAuth
  // flow. Generate the token once on a local machine and set GMAIL_TOKEN_JSON.
  if (isRailway()) {
    throw new Error(
      "Gmail OAuth token missing on Railway. Set GMAIL_TOKEN_JSON with a token generated by the Gmail OAuth flow."
    );
  }

  const auth = await authenticate({
    scopes: SCOPES,
    keyfilePath: CREDENTIALS_PATH,
  });

  const token = auth.credentials;

  fs.writeFileSync(
    TOKEN_PATH,
    JSON.stringify(token, null, 2),
    { mode: 0o600 }
  );

  gmailClient = google.gmail({
    version: "v1",
    auth,
  });

  return gmailClient;
}

async function testGmail() {
  const gmail = await getGmailClient();
  const result = await gmail.users.messages.list({
    userId: "me",
    maxResults: 5,
  });
  return result.data.messages || [];
}

module.exports = {
  getGmailClient,
  testGmail,
};
