/**
 * Server 1 / Grizzly country catalogue
 *
 * countryCode = Grizzly country code
 * countryName = Grizzly country name
 * emoji       = generated flag emoji
 */

const countries = [
  ["74", "Afghanistan"],
  ["155", "Albania"],
  ["58", "Algeria"],
  ["10161", "American Samoa"],
  ["1062", "Andorra"],
  ["76", "Angola"],
  ["181", "Anguilla"],
  ["169", "Antigua and Barbuda"],
  ["39", "Argentina"],
  ["148", "Armenia"],
  ["179", "Aruba"],
  ["175", "Australia"],
  ["50", "Austria"],
  ["35", "Azerbaijan"],
  ["122", "Bahamas"],
  ["145", "Bahrain"],
  ["60", "Bangladesh"],
  ["118", "Barbados"],
  ["51", "Belarus"],
  ["82", "Belgium"],
  ["124", "Belize"],
  ["120", "Benin"],
  ["1003", "Bermuda"],
  ["158", "Bhutan"],
  ["92", "Bolivia"],
  ["108", "Bosnia and Herzegovina"],
  ["123", "Botswana"],
  ["73", "Brazil"],
  ["121", "Brunei Darussalam"],
  ["83", "Bulgaria"],
  ["152", "Burkina Faso"],
  ["119", "Burundi"],
  ["24", "Cambodia"],
  ["41", "Cameroon"],
  ["36", "Canada"],
  ["186", "Cape Verde"],
  ["170", "Cayman islands"],
  ["125", "Central African Republic"],
  ["42", "Chad"],
  ["151", "Chile"],
  ["3", "China"],
  ["33", "Colombia"],
  ["133", "Comoros"],
  ["93", "Costa Rica"],
  ["45", "Croatia"],
  ["113", "Cuba"],
  ["77", "Cyprus"],
  ["63", "Czech Republic"],
  ["18", "DR Congo"],
  ["172", "Denmark"],
  ["168", "Djibouti"],
  ["126", "Dominica"],
  ["109", "Dominican Republic"],
  ["105", "Ecuador"],
  ["21", "Egypt"],
  ["167", "Equatorial Guinea"],
  ["176", "Eritrea"],
  ["34", "Estonia"],
  ["71", "Ethiopia"],
  ["189", "Fiji"],
  ["163", "Finland"],
  ["78", "France"],
  ["162", "French Guiana"],
  ["1012", "French Polynesia"],
  ["154", "Gabon"],
  ["28", "Gambia"],
  ["128", "Georgia"],
  ["43", "Germany"],
  ["38", "Ghana"],
  ["201", "Gibraltar"],
  ["129", "Greece"],
  ["1008", "Greenland"],
  ["127", "Grenada"],
  ["160", "Guadeloupe"],
  ["94", "Guatemala"],
  ["68", "Guinea"],
  ["130", "Guinea-Bissau"],
  ["131", "Guyana"],
  ["26", "Haiti"],
  ["88", "Honduras"],
  ["14", "Hong Kong"],
  ["84", "Hungary"],
  ["132", "Iceland"],
  ["22", "India"],
  ["6", "Indonesia"],
  ["10016", "Iran"],
  ["47", "Iraq"],
  ["23", "Ireland"],
  ["13", "Israel"],
  ["86", "Italy"],
  ["27", "Ivory Coast"],
  ["103", "Jamaica"],
  ["182", "Japan"],
  ["116", "Jordan"],
  ["2", "Kazakhstan"],
  ["8", "Kenya"],
  ["203", "Kosovo"],
  ["100", "Kuwait"],
  ["11", "Kyrgyzstan"],
  ["25", "Laos"],
  ["49", "Latvia"],
  ["153", "Lebanon"],
  ["136", "Lesotho"],
  ["135", "Liberia"],
  ["102", "Libya"],
  ["10348", "Liechtenstein"],
  ["44", "Lithuania"],
  ["165", "Luxembourg"],
  ["20", "Macao"],
  ["17", "Madagascar"],
  ["137", "Malawi"],
  ["7", "Malaysia"],
  ["159", "Maldives"],
  ["69", "Mali"],
  ["199", "Malta"],
  ["1011", "Martinique"],
  ["114", "Mauritania"],
  ["157", "Mauritius"],
  ["54", "Mexico"],
  ["85", "Moldova"],
  ["144", "Monaco"],
  ["72", "Mongolia"],
  ["171", "Montenegro"],
  ["180", "Montserrat"],
  ["37", "Morocco"],
  ["80", "Mozambique"],
  ["5", "Myanmar"],
  ["138", "Namibia"],
  ["81", "Nepal"],
  ["48", "Netherlands"],
  ["185", "New Caledonia"],
  ["67", "New Zealand"],
  ["90", "Nicaragua"],
  ["139", "Niger"],
  ["19", "Nigeria"],
  ["204", "Niue"],
  ["183", "North Macedonia"],
  ["174", "Norway"],
  ["107", "Oman"],
  ["66", "Pakistan"],
  ["188", "Palestine"],
  ["112", "Panama"],
  ["79", "Papua New Guinea"],
  ["87", "Paraguay"],
  ["65", "Peru"],
  ["4", "Philippines"],
  ["15", "Poland"],
  ["117", "Portugal"],
  ["97", "Puerto Rico"],
  ["111", "Qatar"],
  ["150", "Republic of the Congo"],
  ["146", "Reunion"],
  ["32", "Romania"],
  ["140", "Rwanda"],
  ["134", "Saint Kitts and Nevis"],
  ["164", "Saint Lucia"],
  ["166", "Saint Vincent"],
  ["101", "Salvador"],
  ["10231", "Samoa"],
  ["178", "Sao Tome and Principe"],
  ["53", "Saudi Arabia"],
  ["61", "Senegal"],
  ["29", "Serbia"],
  ["184", "Seychelles"],
  ["115", "Sierra Leone"],
  ["10351", "Singapore"],
  ["10349", "Sint Maarten"],
  ["141", "Slovakia"],
  ["59", "Slovenia"],
  ["149", "Somalia"],
  ["31", "South Africa"],
  ["10350", "South Korea"],
  ["177", "South Sudan"],
  ["56", "Spain"],
  ["64", "Sri Lanka"],
  ["142", "Suriname"],
  ["106", "Swaziland"],
  ["46", "Sweden"],
  ["173", "Switzerland"],
  ["110", "Syria"],
  ["55", "Taiwan"],
  ["143", "Tajikistan"],
  ["9", "Tanzania"],
  ["52", "Thailand"],
  ["91", "Timor-Leste"],
  ["99", "Togo"],
  ["10227", "Tonga"],
  ["104", "Trinidad and Tobago"],
  ["89", "Tunisia"],
  ["62", "Turkey"],
  ["161", "Turkmenistan"],
  ["187", "USA"],
  ["12", "USA (virtual)"],
  ["75", "Uganda"],
  ["1", "Ukraine"],
  ["95", "United Arab Emirates"],
  ["16", "United Kingdom"],
  ["156", "Uruguay"],
  ["40", "Uzbekistan"],
  ["1007", "Vanuatu"],
  ["70", "Venezuela"],
  ["10", "Vietnam"],
  ["30", "Yemen"],
  ["147", "Zambia"],
  ["96", "Zimbabwe"],
];

/*
 * Country name -> ISO alpha-2.
 * Used only to generate the flag emoji.
 */
const special = {
  "USA": "US",
  "USA (virtual)": "US",
  "DR Congo": "CD",
  "Republic of the Congo": "CG",
  "Salvador": "SV",
  "Ivory Coast": "CI",
  "Swaziland": "SZ",
  "Czech Republic": "CZ",
  "South Korea": "KR",
  "North Macedonia": "MK",
  "Hong Kong": "HK",
  "Macao": "MO",
  "Reunion": "RE",
  "Kosovo": "XK",
};

function flagEmoji(alpha2) {
  if (!alpha2 || alpha2.length !== 2) {
    return "🌍";
  }

  return alpha2
    .toUpperCase()
    .split("")
    .map(
      (char) =>
        String.fromCodePoint(
          127397 + char.charCodeAt(0)
        )
    )
    .join("");
}

function getIsoCode(name) {
  if (special[name]) {
    return special[name];
  }

  const normalized = name.toLowerCase();

  const map = {
    afghanistan: "AF",
    albania: "AL",
    algeria: "DZ",
    "american samoa": "AS",
    andorra: "AD",
    angola: "AO",
    anguilla: "AI",
    "antigua and barbuda": "AG",
    argentina: "AR",
    armenia: "AM",
    aruba: "AW",
    australia: "AU",
    austria: "AT",
    azerbaijan: "AZ",
    bahamas: "BS",
    bahrain: "BH",
    bangladesh: "BD",
    barbados: "BB",
    belarus: "BY",
    belgium: "BE",
    belize: "BZ",
    benin: "BJ",
    bermuda: "BM",
    bhutan: "BT",
    bolivia: "BO",
    "bosnia and herzegovina": "BA",
    botswana: "BW",
    brazil: "BR",
    "brunei darussalam": "BN",
    bulgaria: "BG",
    "burkina faso": "BF",
    burundi: "BI",
    cambodia: "KH",
    cameroon: "CM",
    canada: "CA",
    "cape verde": "CV",
    "cayman islands": "KY",
    "central african republic": "CF",
    chad: "TD",
    chile: "CL",
    china: "CN",
    colombia: "CO",
    comoros: "KM",
    "costa rica": "CR",
    croatia: "HR",
    cuba: "CU",
    cyprus: "CY",
    "czech republic": "CZ",
    denmark: "DK",
    djibouti: "DJ",
    dominica: "DM",
    "dominican republic": "DO",
    ecuador: "EC",
    egypt: "EG",
    "equatorial guinea": "GQ",
    eritrea: "ER",
    estonia: "EE",
    ethiopia: "ET",
    fiji: "FJ",
    finland: "FI",
    france: "FR",
    "french guiana": "GF",
    "french polynesia": "PF",
    gabon: "GA",
    gambia: "GM",
    georgia: "GE",
    germany: "DE",
    ghana: "GH",
    gibraltar: "GI",
    greece: "GR",
    greenland: "GL",
    grenada: "GD",
    guadeloupe: "GP",
    guatemala: "GT",
    guinea: "GN",
    "guinea-bissau": "GW",
    guyana: "GY",
    haiti: "HT",
    honduras: "HN",
    hungary: "HU",
    iceland: "IS",
    india: "IN",
    indonesia: "ID",
    iran: "IR",
    iraq: "IQ",
    ireland: "IE",
    israel: "IL",
    italy: "IT",
    jamaica: "JM",
    japan: "JP",
    jordan: "JO",
    kazakhstan: "KZ",
    kenya: "KE",
    kuwait: "KW",
    kyrgyzstan: "KG",
    laos: "LA",
    latvia: "LV",
    lebanon: "LB",
    lesotho: "LS",
    liberia: "LR",
    libya: "LY",
    liechtenstein: "LI",
    lithuania: "LT",
    luxembourg: "LU",
    madagascar: "MG",
    malawi: "MW",
    malaysia: "MY",
    maldives: "MV",
    mali: "ML",
    malta: "MT",
    martinique: "MQ",
    mauritania: "MR",
    mauritius: "MU",
    mexico: "MX",
    moldova: "MD",
    monaco: "MC",
    mongolia: "MN",
    montenegro: "ME",
    montserrat: "MS",
    morocco: "MA",
    mozambique: "MZ",
    myanmar: "MM",
    namibia: "NA",
    nepal: "NP",
    netherlands: "NL",
    "new caledonia": "NC",
    "new zealand": "NZ",
    nicaragua: "NI",
    niger: "NE",
    nigeria: "NG",
    niue: "NU",
    norway: "NO",
    oman: "OM",
    pakistan: "PK",
    palestine: "PS",
    panama: "PA",
    paraguay: "PY",
    peru: "PE",
    philippines: "PH",
    poland: "PL",
    portugal: "PT",
    "puerto rico": "PR",
    qatar: "QA",
    reunion: "RE",
    romania: "RO",
    rwanda: "RW",
    samoa: "WS",
    "saudi arabia": "SA",
    senegal: "SN",
    serbia: "RS",
    seychelles: "SC",
    "sierra leone": "SL",
    singapore: "SG",
    "sint maarten": "SX",
    slovakia: "SK",
    slovenia: "SI",
    somalia: "SO",
    "south africa": "ZA",
    "south sudan": "SS",
    spain: "ES",
    "sri lanka": "LK",
    suriname: "SR",
    sweden: "SE",
    switzerland: "CH",
    syria: "SY",
    taiwan: "TW",
    tajikistan: "TJ",
    tanzania: "TZ",
    thailand: "TH",
    "timor-leste": "TL",
    togo: "TG",
    tonga: "TO",
    "trinidad and tobago": "TT",
    tunisia: "TN",
    turkey: "TR",
    turkmenistan: "TM",
    uganda: "UG",
    ukraine: "UA",
    "united arab emirates": "AE",
    "united kingdom": "GB",
    uruguay: "UY",
    uzbekistan: "UZ",
    vanuatu: "VU",
    venezuela: "VE",
    vietnam: "VN",
    yemen: "YE",
    zambia: "ZM",
    zimbabwe: "ZW",
  };

  return map[normalized] || null;
}

module.exports = countries.map(
  ([countryCode, countryName]) => ({
    countryCode,
    countryName,
    emoji: flagEmoji(
      getIsoCode(countryName)
    ),
  })
);
